import { test } from '@playwright/test';

test('test', async ({ page }) => {
  test.setTimeout(1000000);
  await page.goto('https://mktlab.app/');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Entrar com Google' }).click();
  const page1 = await page1Promise;
  await page1.getByLabel('Email or phone').click();
  await page1.getByLabel('Email or phone').fill('alisson.munhoz@gmail.com');
  await page1.getByLabel('Email or phone').press('Enter' );
  await page1.getByLabel('Try again').click();
  await page1.getByLabel('Email or phone').click();
  await page1.getByLabel('Email or phone').fill('aliisson.munhoz@v4company.com');
  await page1.getByLabel('Email or phone').press('Enter');
  await page1.getByLabel('Email or phone').click();
  await page1.getByLabel('Email or phone').click();
  await page1.getByLabel('Email or phone').press('ArrowLeft' );
  await page1.getByLabel('Email or phone').press('ArrowLeft' );
  await page1.getByLabel('Email or phone').press('ArrowLeft' );
  await page1.getByLabel('Email or phone').press('ArrowLeft' );
  await page1.getByLabel('Email or phone').press('ArrowLeft' );
  await page1.getByLabel('Email or phone').press('ArrowLeft' );
  await page1.getByLabel('Email or phone').press('ArrowLeft' );
  await page1.getByLabel('Email or phone').press('ArrowLeft' );
  await page1.getByLabel('Email or phone').press('ArrowLeft' );
  await page1.getByLabel('Email or phone').press('ArrowLeft' );
  await page1.getByLabel('Email or phone').press('ArrowLeft' );
  await page1.getByLabel('Email or phone').press('ArrowLeft' );
  await page1.getByLabel('Email or phone').press('ArrowLeft' );
  await page1.getByLabel('Email or phone').press('ArrowLeft' );
  await page1.getByLabel('Email or phone').press('ArrowLeft' );
  test.setTimeout(1000000);
  await page1.getByLabel('Email or phone').press('ArrowLeft' );
  await page1.getByLabel('Email or phone').press('ArrowLeft' );
  await page1.getByLabel('Email or phone').press('ArrowLeft' );
  await page1.getByLabel('Email or phone').press('ArrowLeft' );
  await page1.getByLabel('Email or phone').press('ArrowLeft' );
  await page1.getByLabel('Email or phone').press('ArrowLeft' );
  await page1.getByLabel('Email or phone').press('ArrowLeft' );
  await page1.getByLabel('Email or phone').press('ArrowLeft' );
  await page1.getByLabel('Email or phone').press('ArrowLeft' );
  await page1.getByLabel('Email or phone').fill('alisson.munhoz@v4company.com');
  await page1.getByRole('button', { name: 'Next' }).click();
  await page1.getByLabel('Enter your password').click();
  await page1.getByLabel('Enter your password').fill('');
  await page1.getByLabel('Enter your password').press('Enter');
  await page.locator('a').filter({ hasText: 'lightbulb Produtos V4 expand_more' }).click();
  await page.locator('a').filter({ hasText: 'share Rede V4 expand_more' }).click();
  await page.locator('a').filter({ hasText: 'apartment Headquarter' }).click();
  await page.getByPlaceholder('Busque por investidor, mandato...').click();
  await page.getByPlaceholder('Busque por investidor, mandato...').fill('alisson');
  await page.locator('div').filter({ hasText: /^personAlisson Munhoz$/ }).first().click();
  await page.getByRole('button', { name: 'Salvar Permissões' }).click();
  await page.locator('.sc-jIILKH > svg').click();
  await page.getByText('A', { exact: true }).click();
  await page.getByRole('button', { name: 'logout Fazer Logout' }).click();
  test.setTimeout(1000000);
});